name: Zip and Upload Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        

    - name: Read version from manifest.json
      id: version
      run: |
        VERSION=$(jq -r '.version' manifest.json)
        echo "VERSION_TAG=v$VERSION" >> $GITHUB_ENV
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT

    - name: Get latest tag
      id: latest_tag
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0")
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    - name: Check if version updated
      id: check_version
      run: |
        echo "Current version: $VERSION_TAG"
        echo "Latest tag: $LATEST_TAG"
        if [ "$VERSION_TAG" = "$LATEST_TAG" ]; then
          echo "Version not updated, skipping release."
          echo "updated=false" >> $GITHUB_OUTPUT
        else
          echo "Version updated, proceeding with release."
          echo "updated=true" >> $GITHUB_OUTPUT
        fi

    - name: Create ZIP archive
      if: steps.check_version.outputs.updated == 'true'
      run: |
        zip -r prettify-hku-chatgpt.zip . -x "*.git*" -x ".*" -x "assets/*"

    - name: Create GitHub Release
      if: steps.check_version.outputs.updated == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: Release ${{ steps.version.outputs.tag }}
        files: prettify-hku-chatgpt.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
